### ISSUE TITLE
Docker build Failed

### ISSUE THREAD

**Issue by sh7jacobi** [fyangneil/Clustered-Object-Detection-in-Aerial-Image#13]
I assume that there are problems with versions. For example, last version of opencv is not supported by python2. In this docker is used the python2. Also there is the same problem with versions in Makefile. I have following error whe I tried build image:

Sending build context to Docker daemon   2.56kB
Step 1/13 : FROM caffe2/caffe2:snapshot-py2-cuda9.0-cudnn7-ubuntu16.04
 ---> 9ae3e8ea7508
Step 2/13 : RUN mv /usr/local/caffe2 /usr/local/caffe2_build
 ---> Running in 2abdac48148b
Removing intermediate container 2abdac48148b
 ---> 503c9b0f8aa8
Step 3/13 : ENV Caffe2_DIR /usr/local/caffe2_build
 ---> Running in 699c12f84ea8
Removing intermediate container 699c12f84ea8
 ---> f78427f19f73
Step 4/13 : ENV PYTHONPATH /usr/local/caffe2_build:${PYTHONPATH}
 ---> Running in 078416a82979
Removing intermediate container 078416a82979
 ---> b23b5a00e31d
Step 5/13 : ENV LD_LIBRARY_PATH /usr/local/caffe2_build/lib:${LD_LIBRARY_PATH}
 ---> Running in 9f151a82156c
Removing intermediate container 9f151a82156c
 ---> 93074f132a1a
Step 6/13 : RUN git clone https://github.com/facebookresearch/detectron /detectron
 ---> Running in dd2bde1461d5
Cloning into '/detectron'...
Removing intermediate container dd2bde1461d5
 ---> f5e3fb41f62f
Step 7/13 : RUN pip install -r /detectron/requirements.txt
 ---> Running in 4ccf10c815ae
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python2.7/dist-packages (from -r /detectron/requirements.txt (line 1))
Collecting pyyaml==3.12 (from -r /detectron/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz (253kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python2.7/dist-packages (from -r /detectron/requirements.txt (line 3))
Collecting opencv-python>=3.2 (from -r /detectron/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a1/d6/8422797e35f8814b1d9842530566a949d9b5850a466321a6c1d5a99055ee/opencv-python-4.3.0.38.tar.gz (88.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HR7dOV/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ImportError: No module named skbuild

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HR7dOV/opencv-python/
You are using pip version 9.0.1, however version 21.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by fyangneil** [comment]
@sh7jacobi  i did not compile the project in docker, you can try to install detectron (caffe2 version) first, if it is done successfully, you should be able to install this project
